name: 'Deploy Cloud Functions - Node 20'
author: 'jsryudev <jsryu.dev@gmail.com>'
description: 'A GitHub Action to deploy to Firebase Cloud Functions'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'cloud'
  color: 'black'
